//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenItem
    {
        public int OrdenItemId { get; set; }
        public Nullable<int> OrdenId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
